[tool.poetry]
name = "sshbruteforcing"
version = "0.1.0"
description = ""
authors = ["shdennlin <shawndennislin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
paramiko = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
